---
#══════════════════════════════════════════════════════════════════════════════
# ▶ CONFIG  •  MEDIA  •  PS4  •  RADIO STATIONS ◀
# ⟫⟫ Description: Contains the HA configuration for media components.
# ⟫⟫ File: /config/hestia/core/config/preferences/media.config.yaml
# ▶ station name • URL • homepage • favicon • codec • bitrate • language  ◀
#══════════════════════════════════════════════════════════════════════════════
_meta:
  version: 1.1
  updated: 2025-08-10

plex_config:
  host: http://192.168.0.104:32400
  device: dsplus220
  keys:
    token: !secret PLEX_TOKEN
    library:
      tv_shows: 7
      movies: 8
  dependencies:
    - script.matrix_control

# ══ station name • URL • homepage • favicon • codec • bitrate • language ══
radio_config:
stations:
  - name: Qmusic Belgium
    media_content_id: https://icecast-qmusicbe-cdp.triple-it.nl/qmusic.aac
    media_content_type: music
    homepage: https://qmusic.be/
    favicon: https://qmusic.be/assets/favicon/default-67977c4f518d45d3a639958e1c6c072532dd2e05cbef9e42cb9f8ecde1964c97.ico
    codec: AAC+
    bitrate: 96
    language: nl

  - name: JOE
    media_content_id: https://icecast-qmusicbe-cdp.triple-it.nl/joe.mp3
    media_content_type: music
    homepage: https://joe.be/
    favicon: https://cdn-profiles.tunein.com/s25741/images/logog.jpg?t=1
    codec: MP3
    bitrate: 128
    language: nl

  - name: Studio Brussel
    media_content_id: http://icecast.vrtcdn.be/stubru-high.mp3
    media_content_type: music
    homepage: https://www.stubru.be/
    favicon: https://upload.wikimedia.org/wikipedia/commons/9/98/Studio_Brussel_logo_%282023-%29.svg
    codec: MP3
    bitrate: 0
    language: nl

  - name: MNM
    media_content_id: http://icecast.vrtcdn.be/mnm-high.mp3
    media_content_type: music
    homepage: https://www.mnm.be/
    favicon: https://upload.wikimedia.org/wikipedia/commons/0/02/MNM_logo_2024.svg
    codec: MP3
    bitrate: 0
    language: nl

  - name: VRT Radio 1
    media_content_id: http://icecast.vrtcdn.be/radio1-high.mp3
    media_content_type: music
    homepage: https://radio1.be/
    favicon: https://upload.wikimedia.org/wikipedia/commons/0/08/VRT_Radio_1_logo.svg
    codec: MP3
    bitrate: 0
    language: nl

  - name: RTBF La Première
    media_content_id: https://radios.rtbf.be/laprem1ere-64.aac
    media_content_type: music
    homepage: https://www.rtbf.be/lapremiere/
    favicon: https://www.static.rtbf.be/rtbf/home/images/ico/favicon-info-32x32.png
    codec: MP3
    bitrate: 0
    language: fr

  - name: De Tijdloze
    media_content_id: http://icecast.vrtcdn.be/stubru_tijdloze-high.mp3
    media_content_type: music
    homepage: https://www.stubru.be/
    favicon: https://upload.wikimedia.org/wikipedia/commons/5/56/De_Tijdloze.png
    codec: MP3
    bitrate: 0
    language: nl

  - name: TOPradio Belgium
    media_content_id: http://str.topradio.be/topradio.mp3
    media_content_type: music
    homepage: https://www.topradio.be/
    favicon: https://www.topradio.be/favicons/favicon-96x96.png
    codec: MP3
    bitrate: 192
    language: ""

  - name: Tomorrowland One World Radio
    media_content_id: https://playerservices.streamtheworld.com/api/livestream-redirect/OWR_INTERNATIONAL_ADP.aac
    media_content_type: music
    homepage: https://www.tomorrowland.com/home/radio
    favicon: https://www.tomorrowland.com/home/apple-touch-icon.png
    codec: AAC+
    bitrate: 256
    language: en
