registrar: "Ionos"
authoritative_nameservers:
  - "toby.ns.cloudflare.com"
  - "mary.ns.cloudflare.com"
apex_domain: "xplab.io"
apex_records:
  A:
    xplab.io: "217.160.0.86"
    www.xplab.io: "217.160.0.86"
  AAAA:
    xplab.io: "2001:8d8:100f:f000::200"
subdomains:
  nas.xplab.io:
    proxy: true
    tunnel_target: "https://192.168.0.104:5001"
  home.xplab.io:
    proxy: false
  clapham.xplab.io:
    proxy: false

tunnel:
  name: "synology-dsm"
  fallback: "HTTP 404"
  origin_cert: "not configured"
  tailscale_serve_enabled: false

routing:
  magicdns_enabled: true
  search_domain: "reverse-beta.ts.net"
  tailscale_dns: "100.100.100.100"
  fallback_resolvers:
    - "8.8.8.8"
    - "8.8.4.4"
    - "1.1.1.1"
